apiVersion: v1
kind: Pod
metadata:
  name: inflate-test
spec:
  containers:
  - name: inflate
    image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"